### ISSUE TITLE
greek text

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/BUR#2]
Addition of Greek text provided by @Andhrabharati ([reference](https://github.com/sanskrit-lexicon/csl-devanagari/issues/37)).

**Comment by funderburkjim** [comment]
Please refer to  readme.txt at folder [greek](https://github.com/sanskrit-lexicon/BUR/tree/master/greek).

665 lines modified.

**Comment by gasyoun** [comment]
Thanks to @Andhrabharati and @funderburkjim

**Comment by Andhrabharati** [comment]
> Please refer to readme.txt at folder [greek](https://github.com/sanskrit-lexicon/BUR/tree/master/greek).

@funderburkjim 
The readme.txt has
> READY TO UPLOAD.  CHANGE display of greek in BUR and BOP.

Why not include BEN (which has been updated with the greek strings) also as a set, to complete all the pending greek works at once?
https://github.com/sanskrit-lexicon/csl-orig/issues/836#issuecomment-1115115848

**Comment by funderburkjim** [comment]
Good idea to add the Benfey Greek.  Progress will be discussed at https://github.com/sanskrit-lexicon/BEN/issues/6.

**Comment by funderburkjim** [comment]
[proof_greek.txt](https://github.com/sanskrit-lexicon/BUR/blob/master/greek/proof_greek.txt) constructed for potential proofreading of Greek text by @jmigliori or someone else.

**Comment by drdhaval2785** [comment]
Any update @jmigliori or @AnnaRybakovaT ?
