### ISSUE TITLE
Proofread Greek text

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/BUR#4]
@AnnaRybakovaT  This issue devoted to proofreading the Greek text in Burnouf Sanskrit-French dictionary.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT Instructions are in [readme.txt](https://github.com/sanskrit-lexicon/BUR/blob/master/burissues/issue4/readme.txt).

Suggestion:  After you make the first correction to temp_bur_1.txt,
generate 'change_1.txt' and push, and I'll examine.
Once this procedure is verified to be working properly, continue with proofreading the rest of the Greek text.

Note: It is possible that there are NO corrections needed to any of the Greek text instances!

**Comment by AnnaRybakovaT** [comment]
> generate 'change_1.txt' and push, and I'll examine.

Dear Jim,

The program python diff_to_changes_dict.py  works correct:
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/sanskrit-lexicon/BUR/burissues/issue4 (master)
$ python diff_to_changes_dict.py temp_bur_0.txt temp_bur_1.txt change_1.txt
3 changes written to change_1.txt
```
But I can't  push change_1.txt :
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/sanskrit-lexicon/BUR/burissues/issue4 (master)
$ git push
remote: Permission to sanskrit-lexicon/BUR.git denied to AnnaRybakovaT.
fatal: unable to access 'https://github.com/sanskrit-lexicon/BUR/': The requested URL returned error: 403
```

**Comment by drdhaval2785** [comment]
Try again. I have given you write access to the repository.

**Comment by AnnaRybakovaT** [comment]
> Try again. I have given you write access to the repository.

Thanks a lot!

**Comment by funderburkjim** [comment]
## The Greek 'phi' 
In recent work with Greek in MW, it was [observed](https://github.com/sanskrit-lexicon/MWS/issues/153#issuecomment-1438995519) that MW uses the 'Unicode u+03d5  greek symbol phi' Character. (ref: https://www.fileformat.info/info/unicode/char/03d5/index.htm)

Interestingly, Burnouf uses the 'Unicode h+03c6 greek small letter phi' character (https://www.fileformat.info/info/unicode/char/03c6/index.htm)

Here is example, under headword iBa (page 89,2 of Burnouf)

<img width="652" alt="image" src="https://user-images.githubusercontent.com/6393033/220820150-04345174-fa3e-4f25-9b23-150041cd31a5.png">

And the bur.txt digitization has 49 instances of φ
and 0 instances of ϕ, which is consistent with the printed text.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT  

Have installed your corrections.
Noticed there to be only 15 changes.
Probably you have more to come?

If so, please do a 'git pull' (to get a few changes to readme.txt).

Then continue as before, making changes to your temp_bur_1.txt, etc.

**Comment by AnnaRybakovaT** [comment]
> Probably you have more to come?

Dear Jim,
 I have checked only a half of the dictionary, so I suppose to be more corrections.

**Comment by AnnaRybakovaT** [comment]
> Then continue as before, making changes to your temp_bur_1.txt, etc.

Dear Jim,
The file change_1.txt is ready.
The new corrected cases start from line 87386:
```
; <L>13071<pc>493,1<k1>marakata<k2>marakata
87386 old <lang n="greek">λάραγδος</lang>.
;
87386 new <lang n="greek">μάραγδος</lang>.
```

**Comment by funderburkjim** [comment]
## new changes made.

@AnnaRybakovaT  -  The additional changes are installed.

Note: For technical reasons, I separated your combined change_1.txt into two pieces,
* the ones previously submitted. These are now in the change_1.txt file
* the new ones.  These are now in the change_2.txt file.

Altogether, 34 changes.

All done?  Can we close this issue.

**Comment by AnnaRybakovaT** [comment]
> All done? Can we close this issue.

Dear Jim,
From my side the proofreading is finished.
I am ready to check the BOP file.

**Comment by Andhrabharati** [comment]
I do not know why, but I feel another person looking again at BEN's greek words would be better.

If Anna can spend her time, it would be good; else I myself can try seeing it once.

**Comment by funderburkjim** [comment]
@Andhrabharati   I think @jmigliori has done the review of BEN greek, and found no problems.
See https://github.com/sanskrit-lexicon/BEN/issues/8#issuecomment-1418016653

So BOP would be the next one for Anna.  Do you agree?

**Comment by Andhrabharati** [comment]
Yes @funderburkjim !

I know that Jonathan has seen the BEN work and did not find any error at all, which is somewhat surprising for me.
Hence, my above post; probably @AnnaRybakovaT could take it up after finishing the BOP work.

BTW, the BOP work also needs Arabic (22), Avestan (43), Russian (26) and Slavonic (37) entries to be verified once by someone.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT 

Do you want to do the BOP Greek text proofreading 
* now?   If so, I'll prepare BOP now for you
* or later in the year, after the summer season?  If so, I'll wait until then to prepare BOP for you.

**Comment by AnnaRybakovaT** [comment]
> * now?   If so, I'll prepare BOP now for you

Dear Jim,
Yes, I can do it now.

**Comment by Andhrabharati** [comment]
> @Andhrabharati I think @jmigliori has done the review of BEN greek, and found no problems. See [sanskrit-lexicon/BEN#8 (comment)](https://github.com/sanskrit-lexicon/BEN/issues/8#issuecomment-1418016653)
> 
> So BOP would be the next one for Anna. Do you agree?

@funderburkjim 

Just to see if my feeling is valid, had a quick look at a small portion of BEN (the Addenda section), and the results are in 
[ben_Addenda_changes.txt](https://github.com/sanskrit-lexicon/BUR/files/11061334/ben_Addenda_changes.txt)

One can know at once (looking at this file) that some spelling errors do exist in the Greek data [leave apart the punctuation errors].

Hope I made my point clear enough.

**Comment by funderburkjim** [comment]
@Andhrabharati and @AnnaRybakovaT  Comment above to remind us of need for Benfey Greek Proofreading by Anna after the BOP review.


Am considering this Burnouf Greek proofreading issue completed, so closing this issue now.
